ALTER TABLE DOC
 ADD CONSTRAINT FK_LibID_Doc FOREIGN KEY(LibID) REFERENCES BRANCH (LibID);, 
 CONSTRAINT FK_PublisherID FOREIGN KEY(PublisherID) REFERENCES PUBLISHER (PublisherID);

ALTER TABLE RENT MODIFY COLUMN PublisherID BIGINT NOT NULL,
 ADD CONSTRAINT PublisherID fk
 FOREIGN KEY(PublisherID)
 REFERENCES RENT(PUBLISHER);
 
 
ALTER TABLE PUBLISHER MODIFY COLUMN DocID BIGINT NOT NULL,
 ADD CONSTRAINT DocID fk
 FOREIGN KEY(DocID)
 REFERENCES PUBLISHER (DOC), 
 ALTER TABLE PUBLISHER MODIFY COLUMN LibID BIGINT NOT NULL,
 ADD CONSTRAINT LibID fk
 FOREIGN KEY(LibID)
 REFERENCES PUBLISHER (BRANCH);
 
 ALTER TABLE BRANCH MODIFY COLUMN DocID BIGINT NOT NULL,
 ADD CONSTRAINT DocID fk
 FOREIGN KEY(DocID)
 REFERENCES BRANCH (DOC),
 ALTER TABLE BRANCH MODIFY COLUMN PublisherID BIGINT NOT NULL, ADD CONSTRAINT PublisherID fk
 FOREIGN KEY(PublisherID)
 REFERENCES BRANCH (PUBLISHER);
 
 ALTER TABLE CHIEF_EDITOR MODIFY COLUMN AuthorID BIGINT NOT NULL,
 ADD CONSTRAINT AuthorID fk
 FOREIGN KEY(AuthorID)
 REFERENCES CHIEF_EDITOR (BOOK);
 
 ALTER TABLE BOOK MODIFY COLUMN ChiefEdID BIGINT NOT NULL,
 ADD CONSTRAINT ChiefEdID fk
 FOREIGN KEY(ChiefEdID)
 REFERENCES BOOK (CHIEF_EDITOR);
 
 ALTER TABLE JOURNAL_VOL MODIFY COLUMN ChiefEdID BIGINT NOT NULL,
 ADD CONSTRAINT ChiefEdID fk
 FOREIGN KEY(ChiefEdID)
 REFERENCES JOURNAL_VOL (CHIEF_EDITOR),
 ALTER TABLE JOURNAL_VOL MODIFY COLUMN AuthorID BIGINT NOT NULL, ADD CONSTRAINT PublisherID fk
 FOREIGN KEY(AuthorID)
 REFERENCES JOURNAL_VOL (BOOK);
  
 ALTER TABLE JOURNAL_ISSUE MODIFY COLUMN IssueNum BIGINT NOT NULL,
 ADD CONSTRAINT IssueNum fk
 FOREIGN KEY(IssueNum)
 REFERENCES JOURNAL_ISSUE (JOURNAL_vOL;