CREATE TABLE RESERVE
(
ResTime	DATETIME NOT NULL DEFAULT SYSDATE PRIMARY KEY,
STATUS	CHAR (1) NOT NULL DEFAULT "NO",
ResNum	BIGINT UNSIGNED NOT NULL,
LibID	BIGINT UNSIGNED NOT NULL,
DocID	BIGINT UNSIGNED NOT NULL,
CopyNum	BIGINT UNSIGNED NOT NULL	
);

CREATE TABLE Library_Card
(
Address	VARCHAR (100) NOT NULL,
PhoneNum BIGINT UNSIGNED NOT NULL,
RegistrationID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
L_Name VARCHAR (100) NOT NULL,
DocID BIGINT UNSIGNED NOT NULL,
LibID BIGINT UNSIGNED NOT NULL,
PublisherID	BIGINT UNSIGNED NOT NULL
);

CREATE TABLE RENT
(
PublisherID	BIGINT UNSIGNED NOT NULL,
RentDateTime DATETIME NOT NULL DEFAULT SYSDATE,
LibCardID BIGINT UNSIGNED NOT NULL,
ResNum BIGINT UNSIGNED NOT NULL,
LibID BIGINT UNSIGNED NOT NULL,
DocID BIGINT UNSIGNED NOT NULL,
CopyNum	BIGINT UNSIGNED NOT NULL
);

CREATE TABLE PUBLISHER
(
PublisherID	BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
PubAdd VARCHAR (100) NOT NULL,
PubDate DATETIME NOT NULL,
DocID BIGINT UNSIGNED NOT NULL,
LibID BIGINT UNSIGNED NOT NULL

);

CREATE TABLE BRANCH
(
LibID BIGINT NOT NULL PRIMARY KEY,
DocID BIGINT UNSIGNED NOT NULL,
PublisherID	BIGINT UNSIGNED NOT NULL,
LibAdd VARCHAR (100) NOT NULL,
LibName VARCHAR (100) NOT NULL
);


CREATE TABLE CHIEF_EDITOR
(
ChiefEdID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
AuthorID BIGINT UNSIGNED NOT NULL,
DocID BIGINT UNSIGNED NOT NULL,
IssueNum BIGINT UNSIGNED NOT NULL,
ChiefName VARCHAR (100) NOT NULL
);

CREATE TABLE BOOK
(
AuthorID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
ChiefEdID BIGINT UNSIGNED NOT NULL,
DocID BIGINT UNSIGNED NOT NULL,
Auth_Name VARCHAR (100) NOT NULL,
ISBN BIGINT UNSIGNED NOT NULL
);


CREATE TABLE JOURNAL_VOL
(
IssueNum BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DocID BIGINT UNSIGNED NOT NULL,
JournalNum BIGINT UNSIGNED NOT NULL,
ChiefEdID BIGINT UNSIGNED NOT NULL,
AuthorID BIGINT UNSIGNED NOT NULL
);

CREATE TABLE JOURNAL_ISSUE
(
IssueNum BIGINT UNSIGNED NOT NULL,
DocID BIGINT UNSIGNED NOT NULL,
ChiefEdID BIGINT UNSIGNED NOT NULL,
L_Name VARCHAR (100) NOT NULL,
);

COMMIT;